#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#    spring.jpa.hibernate.ddl-auto=none
#    spring.jpa.hibernate.show-sql=true
#    spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#    spring.datasource.username=postgres
#    spring.datasource.password=admin
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/phoneshop_db
#    username: postgres
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update

#=======================use MySQL========================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phoneshop
    username: vengeang
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: false
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
#    driver-class-name: org.postgresql.Driver
#spring.datasource.url=jdbc:mysql://localhost/testproject
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

#  spring.datasource.url=jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC
#  spring.datasource.username=user12
#  spring.datasource.password=s$cret
#
#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect