#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#    spring.jpa.hibernate.ddl-auto=none
#    spring.jpa.hibernate.show-sql=true
#    spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#    spring.datasource.username=postgres
#    spring.datasource.password=admin
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop_db
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#=======================use MySQL========================
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/phoneshop
#    username: vengeang
#    password: root
#    driver-class-name: org.postgresql.Driver
#spring.datasource.url=jdbc:mysql://localhost/testproject
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect